import { useEffect, useState } from "react";
import api from "../services/api";

const emptyForm = {
  CompanyName: "",
  Address1: "",
  Address2: "",
  City: "",
  District: "",
  Pincode: "",
  MobileNumber: "",
  BankCode: "",
};

function Company() {
  const [companies, setCompanies] = useState([]);
  const [banks, setBanks] = useState([]);

  const [form, setForm] = useState(emptyForm);

  const [editingCode, setEditingCode] = useState(null);

  const [search, setSearch] = useState("");

  const [loading, setLoading] = useState(false);

  const [error, setError] = useState("");

  // =====================================================
  // LOAD DATA
  // =====================================================

  useEffect(() => {
    loadData();
  }, []);

  const getArray = (response) => {
    if (Array.isArray(response)) {
      return response;
    }

    if (Array.isArray(response?.data)) {
      return response.data;
    }

    return [];
  };

  const loadData = async () => {
    try {
      setLoading(true);
      setError("");

      const [companyResponse, bankResponse] =
        await Promise.all([
          api.get("/companies"),
          api.get("/banks"),
        ]);

      setCompanies(
        getArray(companyResponse.data)
      );

      setBanks(
        getArray(bankResponse.data)
      );
    } catch (err) {
      console.error(
        "LOAD COMPANY ERROR:",
        err
      );

      setError(
        err.response?.data?.message ||
          "Unable to load company data"
      );
    } finally {
      setLoading(false);
    }
  };

  // =====================================================
  // HANDLE INPUT
  // =====================================================

  const handleChange = (e) => {
    const { name, value } = e.target;

    setForm((previous) => ({
      ...previous,
      [name]: value,
    }));
  };

  // =====================================================
  // SAVE
  // =====================================================

  const saveCompany = async (e) => {
    e.preventDefault();

    setError("");

    if (!form.CompanyName.trim()) {
      setError("Company name is required");
      return;
    }

    if (!form.Address1.trim()) {
      setError("Address 1 is required");
      return;
    }

    if (!form.City.trim()) {
      setError("City is required");
      return;
    }

    if (!form.District.trim()) {
      setError("District is required");
      return;
    }

    if (!/^\d{6}$/.test(form.Pincode.trim())) {
      setError(
        "Pincode must be exactly 6 digits"
      );
      return;
    }

    if (
      !/^[6-9]\d{9}$/.test(
        form.MobileNumber.trim()
      )
    ) {
      setError(
        "Enter valid 10 digit mobile number"
      );
      return;
    }

    try {
      setLoading(true);

      if (editingCode !== null) {
        // UPDATE
        await api.put(
          `/companies/${editingCode}`,
          form
        );
      } else {
        // CREATE
        // CompanyCode is generated by backend
        await api.post(
          "/companies",
          form
        );
      }

      clearForm();

      await loadData();
    } catch (err) {
      console.error(
        "SAVE COMPANY ERROR:",
        err
      );

      setError(
        err.response?.data?.message ||
          "Unable to save company"
      );
    } finally {
      setLoading(false);
    }
  };

  // =====================================================
  // EDIT
  // =====================================================

  const editCompany = (company) => {
    const code = Number(
      company.CompanyCode
    );

    setEditingCode(code);

    setForm({
      CompanyName:
        company.CompanyName || "",

      Address1:
        company.Address1 || "",

      Address2:
        company.Address2 || "",

      City:
        company.City || "",

      District:
        company.District || "",

      Pincode:
        company.Pincode || "",

      MobileNumber:
        company.MobileNumber || "",

      BankCode:
        company.BankCode
          ? String(company.BankCode)
          : "",
    });

    setError("");

    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  // =====================================================
  // DELETE
  // =====================================================

  const deleteCompany = async (
    companyCode
  ) => {
    const confirmed = window.confirm(
      "Are you sure you want to delete this company?"
    );

    if (!confirmed) {
      return;
    }

    try {
      setLoading(true);
      setError("");

      await api.delete(
        `/companies/${companyCode}`
      );

      await loadData();
    } catch (err) {
      console.error(
        "DELETE COMPANY ERROR:",
        err
      );

      setError(
        err.response?.data?.message ||
          "Unable to delete company"
      );
    } finally {
      setLoading(false);
    }
  };

  // =====================================================
  // CLEAR
  // =====================================================

  const clearForm = () => {
    setForm({
      ...emptyForm,
    });

    setEditingCode(null);

    setError("");
  };

  // =====================================================
  // SEARCH
  // =====================================================

  const filteredCompanies =
    companies.filter((company) => {
      const text = `
        ${company.CompanyCode || ""}
        ${company.CompanyName || ""}
        ${company.Address1 || ""}
        ${company.City || ""}
        ${company.District || ""}
        ${company.Pincode || ""}
        ${company.MobileNumber || ""}
        ${company.BankName || ""}
      `;

      return text
        .toLowerCase()
        .includes(
          search.toLowerCase()
        );
    });

  // =====================================================
  // UI
  // =====================================================

  return (
    <div>
      {/* =================================================
          HEADER
      ================================================= */}

      <div className="page-header">
        <div>
          <h2>Company Master</h2>

          <p>
            Manage company information
          </p>
        </div>
      </div>

      {/* =================================================
          FORM
      ================================================= */}

      <div className="master-form-card">
        <h3>
          {editingCode !== null
            ? "Edit Company"
            : "Add Company"}
        </h3>

        {error && (
          <div className="error-message">
            {error}
          </div>
        )}

        <form onSubmit={saveCompany}>
          <div className="form-grid">

            {/* ==========================================
                COMPANY CODE
                HIDDEN INTENTIONALLY
            ========================================== */}

            {/* Company Code is automatically generated.
                It is NOT shown in the form. */}

            {/* ==========================================
                COMPANY NAME
            ========================================== */}

            <div className="form-group">
              <label>
                Company Name *
              </label>

              <input
                type="text"
                name="CompanyName"
                value={
                  form.CompanyName
                }
                onChange={handleChange}
                placeholder="Company name"
                maxLength={50}
              />
            </div>

            {/* ==========================================
                ADDRESS 1
            ========================================== */}

            <div className="form-group">
              <label>
                Address 1 *
              </label>

              <input
                type="text"
                name="Address1"
                value={
                  form.Address1
                }
                onChange={handleChange}
                placeholder="Address 1"
                maxLength={50}
              />
            </div>

            {/* ==========================================
                ADDRESS 2
            ========================================== */}

            <div className="form-group">
              <label>
                Address 2
              </label>

              <input
                type="text"
                name="Address2"
                value={
                  form.Address2
                }
                onChange={handleChange}
                placeholder="Address 2"
                maxLength={50}
              />
            </div>

            {/* ==========================================
                CITY
            ========================================== */}

            <div className="form-group">
              <label>
                City *
              </label>

              <input
                type="text"
                name="City"
                value={form.City}
                onChange={handleChange}
                placeholder="City"
                maxLength={50}
              />
            </div>

            {/* ==========================================
                DISTRICT
            ========================================== */}

            <div className="form-group">
              <label>
                District *
              </label>

              <input
                type="text"
                name="District"
                value={
                  form.District
                }
                onChange={handleChange}
                placeholder="District"
                maxLength={50}
              />
            </div>

            {/* ==========================================
                PINCODE
            ========================================== */}

            <div className="form-group">
              <label>
                Pincode *
              </label>

              <input
                type="text"
                name="Pincode"
                value={
                  form.Pincode
                }
                onChange={handleChange}
                placeholder="6 digit pincode"
                maxLength={6}
                inputMode="numeric"
              />
            </div>

            {/* ==========================================
                MOBILE
            ========================================== */}

            <div className="form-group">
              <label>
                Mobile Number *
              </label>

              <input
                type="text"
                name="MobileNumber"
                value={
                  form.MobileNumber
                }
                onChange={handleChange}
                placeholder="Mobile number"
                maxLength={10}
                inputMode="numeric"
              />
            </div>

            {/* ==========================================
                BANK
            ========================================== */}

            <div className="form-group">
              <label>
                Bank
              </label>

              <select
                name="BankCode"
                value={
                  form.BankCode
                }
                onChange={handleChange}
              >
                <option value="">
                  Select Bank
                </option>

                {banks.map((bank) => (
                  <option
                    key={
                      bank.BankCode
                    }
                    value={
                      bank.BankCode
                    }
                  >
                    {bank.BankName}
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* =================================================
              BUTTONS
          ================================================= */}

          <div className="form-actions">
            <button
              type="submit"
              className="primary-button"
              disabled={loading}
            >
              {loading
                ? "Saving..."
                : editingCode !== null
                ? "Update"
                : "Save"}
            </button>

            <button
              type="button"
              className="secondary-button"
              onClick={clearForm}
              disabled={loading}
            >
              Clear
            </button>
          </div>
        </form>
      </div>

      {/* =================================================
          COMPANY LIST
      ================================================= */}

      <div className="table-card">
        <div className="table-header">
          <h3>Company List</h3>

          <input
            className="search-input"
            type="text"
            placeholder="Search company..."
            value={search}
            onChange={(e) =>
              setSearch(
                e.target.value
              )
            }
          />
        </div>

        <div className="table-wrapper">
          <table>
            <thead>
              <tr>
                <th>
                  Company Code
                </th>

                <th>
                  Company Name
                </th>

                <th>
                  Address
                </th>

                <th>
                  City
                </th>

                <th>
                  District
                </th>

                <th>
                  Pincode
                </th>

                <th>
                  Mobile
                </th>

                <th>
                  Bank
                </th>

                <th>
                  Action
                </th>
              </tr>
            </thead>

            <tbody>
              {filteredCompanies.map(
                (company) => (
                  <tr
                    key={
                      company.CompanyCode
                    }
                  >
                    {/* COMPANY CODE */}
                    <td>
                      {
                        company.CompanyCode
                      }
                    </td>

                    {/* NAME */}
                    <td>
                      {
                        company.CompanyName
                      }
                    </td>

                    {/* ADDRESS */}
                    <td>
                      {
                        company.Address1
                      }
                    </td>

                    {/* CITY */}
                    <td>
                      {company.City}
                    </td>

                    {/* DISTRICT */}
                    <td>
                      {
                        company.District
                      }
                    </td>

                    {/* PINCODE */}
                    <td>
                      {
                        company.Pincode
                      }
                    </td>

                    {/* MOBILE */}
                    <td>
                      {
                        company.MobileNumber
                      }
                    </td>

                    {/* BANK */}
                    <td>
                      {
                        company.BankName ||
                        "-"
                      }
                    </td>

                    {/* ACTION */}
                    <td>
                      <button
                        type="button"
                        className="edit-button"
                        title="Edit"
                        onClick={() =>
                          editCompany(
                            company
                          )
                        }
                      >
                        ✏️
                      </button>

                      <button
                        type="button"
                        className="delete-button"
                        title="Delete"
                        onClick={() =>
                          deleteCompany(
                            company.CompanyCode
                          )
                        }
                      >
                        🗑️
                      </button>
                    </td>
                  </tr>
                )
              )}

              {!loading &&
                filteredCompanies.length ===
                  0 && (
                  <tr>
                    <td
                      colSpan="9"
                      className="empty-row"
                    >
                      No companies found
                    </td>
                  </tr>
                )}

              {loading && (
                <tr>
                  <td
                    colSpan="9"
                    className="empty-row"
                  >
                    Loading...
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export default Company;